name: Workflow to get the secret(s) from AWS Secret Manager.
# - How to Run Python Scripts in GitHub Action Workflows, Data Engineering With Nick, 1.43K subscribers
#   https://www.youtube.com/watch?v=zk4bSTD8uWM

on:
  workflow_dispatch:

jobs:
  go-get-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository.
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.19' # The Go version to download (if necessary) and use.

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - run: |
          go mod init get-secret
          go get github.com/aws/aws-sdk-go-v2
          go get github.com/aws/aws-sdk-go-v2/config
          go get github.com/aws/aws-sdk-go-v2/service/secretsmanager
          go run go/get-secret.go
    if: 1 == 1

  python-get-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository.
        uses: actions/checkout@v4

      - name: Setup Python 3.12.
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Install Python Dependencies.
        run: |
          echo "Install Python Dependencies."
          python -m pip install -r python3/requirements.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run python python3/get-secret.py.
        run: |
            echo "Run python python3/get-secret.py."
            python python3/get-secret.py
    if: 1 == 1
